language: node_js
node_js: stable
sudo: required
dist: trusty

addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
  - node_modules
  - "$HOME/.cache/bower"

install:
- npm install -g bower polymer-cli
- npm install
- bower install

script:
- chmod +x ./gpages_build.sh
- "./gpages_build.sh"

after_success:
- if [ ${TRAVIS_PULL_REQUEST} = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  bower install -s oneezy/build-tools && ./bower_components/build-tools/gpages_build.sh;
  fi



#
# 1.) Install Travis CLI:
# 2.) Write command: travis encrypt GH_TOKEN=**************** --add  
# 3.) Automate command inside .gitconfig so you don't have to remember the token value (optional)
#
#       [alias]
#	      gh-token = "!travis encrypt GH_TOKEN=************************ --add"
#
# 4.) Secure Token Output
#
#       env:
#          global:
#             secure: ZwNuFN1cryC5dff4c3a1qePkoRZoug+HDiN55dFATTt7Opk20C8SgO+RGEWqYWelFkUN2jhAyoJ91GFMxOyYqbqZP+mQfBaFWgBZoKIcGcDur5...
#
